on:
  push:
    tags:
      - v*
name: make release
jobs:
  makerelease:
    name: make release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: make release
        uses: docker://golang:latest
        with:
          args: make release
      - name: update release body
        uses: ncipollo/release-action@v1
          with:
            artifacts: "cross/*"
            bodyFile: "Release.md"
            token: ${{ secrets.GITHUB_TOKEN }}
